name: Coveralls

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  API:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: API install
      run: npm install

    - name: API test
      env:
        DEBUG:
      run: |
        npm run test-coveralls

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage/lcov.info
